[package]
name = "rsurl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rsurl_shortener_backend"
path = "src/main.rs"

[dependencies]
rocket = "0.4.10"
rocket_codegen = "0.4.10"
harsh = "*"
